[user]
name = "LeonRein"
email = "4107480+LeonRein@users.noreply.github.com"

[ui]
editor = "helix"
default-command = ["log", "-r", "ancestors(@, 10) | ancestors(remote_bookmarks().., 2) | heads(ancestors(@, 10)::) | trunk()"]
